# Generated by Django 2.0 on 2019-10-07 14:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_user_id', models.CharField(max_length=80, serialize=False, verbose_name='byUserId')),
                ('to_user_id', models.CharField(max_length=80, serialize=False, verbose_name='toUserId')),
                ('room_id', models.CharField(max_length=80, serialize=False, verbose_name='roomId')),
                ('message', django_mysql.models.JSONField(default=dict, null=True)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='エントリID')),
                ('user_id', models.CharField(max_length=80, serialize=False, verbose_name='ユーザID')),
                ('team_id', models.CharField(max_length=80, null=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(1, 'フルオープン'), (2, '指定チーム')], default=1, max_length=2)),
                ('title', models.CharField(default='', max_length=128, null=True)),
                ('contents', models.TextField(default=dict)),
                ('comment', django_mysql.models.JSONField(default=dict, null=True)),
                ('category', models.IntegerField(default=99, max_length=3, null=True)),
                ('image_path', models.TextField(default='', null=True)),
                ('status', models.IntegerField(choices=[(0, '下書き'), (1, '非公開'), (3, '公開中'), (99, '終了')], default=0, max_length=2)),
                ('entry_start', models.DateTimeField(null=True)),
                ('entry_end', models.DateTimeField(null=True)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('open_dt', models.DateTimeField(null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
                ('update_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0, verbose_name=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49))),
                ('category_name', models.CharField(max_length=40)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='テーブルID')),
                ('request_user_id', models.CharField(max_length=80, serialize=False, verbose_name='リクエストユーザID')),
                ('follower_user_id', models.CharField(max_length=80, serialize=False, verbose_name='リクエストを受けたユーザID')),
                ('follow_dt', models.DateTimeField(auto_now=True, null=True)),
                ('approval', models.SmallIntegerField(default=0)),
                ('approval_dt', models.DateTimeField(auto_now=True, null=True)),
                ('reject', models.SmallIntegerField(default=0)),
                ('reject_dt', models.DateTimeField(auto_now=True, null=True)),
                ('brock_user_id', models.CharField(max_length=80, null=True, serialize=False, verbose_name='ID')),
                ('brock_dt', models.DateTimeField(auto_now=True, null=True)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediate_user_id', models.CharField(max_length=80, serialize=False, verbose_name='ID')),
                ('from_user_id', models.CharField(max_length=40, serialize=False, verbose_name='ID')),
                ('from_approval', models.SmallIntegerField(default=0)),
                ('from_approval_dt', models.DateTimeField(auto_now=True, null=True)),
                ('from_reject', models.SmallIntegerField(default=0)),
                ('from_reject_dt', models.DateTimeField(auto_now=True, null=True)),
                ('to_user_id', models.CharField(max_length=40, serialize=False, verbose_name='ID')),
                ('to_approval', models.SmallIntegerField(default=0)),
                ('to_approval_dt', models.DateTimeField(auto_now=True, null=True)),
                ('to_reject', models.SmallIntegerField(default=0)),
                ('to_reject_dt', models.DateTimeField(auto_now=True, null=True)),
                ('mediated', models.SmallIntegerField(default=0)),
                ('mediated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=80, serialize=False, verbose_name='ユーザID')),
                ('team_id', models.CharField(max_length=80, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(default=0)),
                ('request', models.SmallIntegerField(default=0, null=True)),
                ('request_dt', models.DateTimeField(auto_now=True, null=True)),
                ('approval', models.SmallIntegerField(default=0, null=True)),
                ('approval_dt', models.DateTimeField(auto_now=True, null=True)),
                ('reject', models.SmallIntegerField(default=0, null=True)),
                ('reject_dt', models.DateTimeField(auto_now=True, null=True)),
                ('brock', models.SmallIntegerField(default=0, null=True)),
                ('brock_dt', models.DateTimeField(auto_now=True, null=True)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('update_user_id', models.CharField(max_length=80, null=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=80, null=True, serialize=False, verbose_name='ユーザID')),
                ('team_id', models.CharField(max_length=80, null=True, serialize=False, verbose_name='チームID')),
                ('category', models.SmallIntegerField(default=0, null=True)),
                ('contents', models.TextField()),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=80, null=True, serialize=False, verbose_name='ユーザID')),
                ('news_id', models.CharField(max_length=80, serialize=False, verbose_name='PushID')),
                ('push_id', models.CharField(max_length=80, null=True, serialize=False, verbose_name='PushID')),
                ('status', models.SmallIntegerField(choices=[(0, '未読'), (1, '既読')], default=0, max_length=2)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='チームID')),
                ('name', models.CharField(max_length=80, serialize=False, verbose_name='名前')),
                ('category', models.CharField(default='', max_length=124, null=True, serialize=False, verbose_name='カテゴリ')),
                ('image_path', models.TextField()),
                ('contents', models.CharField(default='', max_length=124, null=True, serialize=False, verbose_name='説明')),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=80, serialize=False, verbose_name='ID')),
                ('like_user_id', models.CharField(max_length=80, serialize=False, verbose_name='ID')),
                ('unlike_dt', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=80, null=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('skill', django_mysql.models.JSONField(default=dict, null=True)),
                ('profile', django_mysql.models.JSONField(default=dict, null=True)),
                ('team', django_mysql.models.JSONField(default=dict, null=True)),
                ('mail', models.EmailField(default='', max_length=254, null=True)),
                ('unsubscribe', models.CharField(choices=[('active', '0'), ('negative', '1')], default='active', max_length=1, null=True)),
                ('type', models.SmallIntegerField(default=1, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('del_flg', models.SmallIntegerField(default=0, max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
