# Generated by Django 2.0 on 2019-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='message',
            new_name='logs',
        ),
        migrations.AlterField(
            model_name='entrycategory',
            name='category_id',
            field=models.IntegerField(default=0, verbose_name=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49)),
        ),
    ]
